#!/bin/bash
printf '%s, ' . ..; find . -maxdepth 1 -type d -name '.?*' -printf '%P/, ' | sort; find . -maxdepth 1 -type d ! -name '.?*' ! -name '.' ! -name '..' -printf '%P/, ' | sort; find . -maxdepth 1 -type f -name '.?*' -printf '%P, ' | sort; find . -maxdepth 1 -type f ! -name '.?*' ! -name '.' ! -name '..' -printf '%P, ' | sort; printf '\n'
